sonar.organization=bryanjuseyo
sonar.projectKey=Bryanjuseyo_SWE5006-Group13
sonar.projectName=CleanMatch

sonar.sources=frontend/src,backend/app
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,backend/tests/**/*.py
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/venv/**,**/__pycache__/**,**/.git/**,**/coverage/**
sonar.coverage.exclusions=backend/tests/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/test/**,frontend/src/main.tsx

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
