sonar.organization=bryanjuseyo
sonar.projectKey=Bryanjuseyo_SWE5006-Group13
sonar.projectName=CleanMatch

sonar.sources=frontend/src,backend/app
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/venv/**,**/__pycache__/**,**/.git/**,**/coverage/**

sonar.python.version=3.12